server:
  port: 8087

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: http://${TRIP_SERVICE_BASEURL:localhost:8085}
          predicates:
            - Path=/trips
            - Method=POST
          filters:
            - SetPath=/api/trip
        - id: trip-service-all
          uri: http://${TRIP_SERVICE_BASEURL:localhost:8085}
          predicates:
            - Path=/trips
            - Method=GET
          filters:
            - SetPath=/api/trip/all
        - id: booking-service
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/bookings
          filters:
            - SetPath=/api/booking
        - id: traveler-service
          uri: http://${TRAVELER_SERVICE_BASEURL:localhost:8086}
          predicates:
            - Path=/travelers
          filters:
            - SetPath=/api/traveler